### ISSUE TITLE
re.error: missing ), unterminated subpattern at position 6

### ISSUE THREAD

**Issue by jayvdb** [AdamGold/pypkgfreeze#10] opened 2019-10-24 03:58 UTC
Running `pkgfreeze` in the `pkgfreeze` repo on Python 3.7 and the last PyPI release of pkgfreeze
```py
pypkgfreeze> pkgfreeze
Traceback (most recent call last):
  File "/usr/bin/pkgfreeze", line 11, in <module>
    load_entry_point('pypkgfreeze==0.1.2', 'console_scripts', 'pkgfreeze')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pypkgfreeze/pypkgfreeze.py", line 43, in main
    altered_setup = freeze_pkgs(setup_path.read_text(), pip_output)
  File "/usr/lib/python3.7/site-packages/pypkgfreeze/pypkgfreeze.py", line 27, in freeze_pkgs
    r"[\'\"]({})[\'\"]".format(name), r'"\1=={}"'.format(version), text
  File "/usr/lib64/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.7/sre_parse.py", line 819, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 6
```

**Comment by AdamGold** [comment] 2019-10-26 07:53
Hello @jayvdb , I'm unable to reproduce it. Can you share your `setup.py`?

**Comment by jayvdb** [comment] 2019-10-26 13:30
That was with the `setup.py` in this repo.

**Comment by AdamGold** [comment] 2019-10-26 18:42
I see. Can you share your `pip freeze` please? I believe it's caused because one of your packages contain parenthesis. Should be fixed in `0.1.3`.

**Comment by jayvdb** [comment] 2019-10-26 21:17
Ya, my pip freeze includes a few entries like
```
# Editable install with no version control (asciimatics==0.0.0)
-e /usr/lib/python3.7/site-packages
```

**Comment by AdamGold** [comment] 2019-10-26 21:18
Fixed :) closing.

**Closed as completed by AdamGold** 2019-10-26 21:18 UTC
